### ISSUE TITLE
What is different from the original apache-tika image?

### ISSUE THREAD

**Issue by ovizii** [LogicalSpark/docker-tikaserver#35]
Trying to figure out which one to use, and this one does not seem to share the reason for its existence :-)

**Comment by EnsuingRequiem** [comment]
I've seen a few composes reference this particular version, and was in the same situation as you. I took a look at the Tika releases from https://tika.apache.org and found out that 1.x branch (which this is based on) is EOL in a month. I'll be going with the original from https://github.com/apache/tika-docker as a result.

**Comment by mpdude** [comment]
I cannot speak for @dameikle, but IIRC he maintained this repo here before he was able to move things to/under the Apache organisation label (see https://github.com/LogicalSpark/docker-tikaserver/issues/22).

So, my personal impression was that this place here is a bit outdated and https://github.com/apache/tika-docker is where the music plays right now.

If my assessment is correct, maybe it would be a good idea to leave a note in the README here, pointing to the Apache repo?

**Comment by dameikle** [comment]
Hello. Yes, @mpdude is correct, I started this repos initially before moving it over to apache/tika-docker (I'm an Apache Tika commiter and PMC member).

It's been in the back of mind for a wee while to retire this image and repos, the up coming 1.x EOL seems like a logical point to do so, so will update the README.

**Comment by ovizii** [comment]
If this is the simple docker-compose.yml I was using, would tika 2 be a drop-in replacement for me?

```
  filerun-tika:                                                                                                                                      
# initiall I used this image
#    image: logicalspark/docker-tikaserver:latest                                                                                                    
# then I switched to this one
    image: apache/tika:1.28.5-full                                                                                                                   
# is it possible to simply switch to version 2?
#    image: apache/tika:latest                                                                                                                       
    container_name: filerun-tika                                                                                                                     
    hostname: filerun-tika                                                                                                                           
    restart: "no"                                                                                                                                    
    networks:                                                                                                                                        
      - filerun                                                                                                                                      
    cpus: 4                                                                                                                                          
    mem_limit: 4G
```
